using DomainRelay.Mapping.SourceGen.Models;
using System.Text;

namespace DomainRelay.Mapping.SourceGen.Emission;

internal static class MappingCodeEmitter
{
    public static string Emit(IReadOnlyList<GeneratedMappingModel> mappings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DomainRelay.Mapping.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedMappings");
        sb.AppendLine("{");

        foreach (var mapping in mappings)
        {
            sb.AppendLine($"    public static {mapping.DestinationTypeDisplayName} {mapping.MappingMethodName}({mapping.SourceTypeDisplayName} source)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (source is null)");
            sb.AppendLine("        {");
            sb.AppendLine("            throw new global::System.ArgumentNullException(nameof(source));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        return new {mapping.DestinationTypeDisplayName}");
            sb.AppendLine("        {");

            for (var i = 0; i < mapping.Members.Count; i++)
            {
                var member = mapping.Members[i];
                var suffix = i == mapping.Members.Count - 1 ? string.Empty : ",";
                sb.AppendLine($"            {member.DestinationMemberName} = {member.SourceAccessCode}{suffix}");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public static object {mapping.BoxedMethodName}(object source)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return {mapping.MappingMethodName}(({mapping.SourceTypeDisplayName})source);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}