using DomainRelay.Mapping.SourceGen.Models;
using System.Text;

namespace DomainRelay.Mapping.SourceGen.Emission;

internal static class RegistryEmitter
{
    public static string Emit(IReadOnlyList<GeneratedMappingModel> mappings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DomainRelay.Mapping.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class GeneratedMappingRegistry : global::DomainRelay.Mapping.Abstractions.Generation.IGeneratedMappingRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly global::System.Collections.Generic.Dictionary<(global::System.Type, global::System.Type), global::System.Func<object, object>> _mappers = new()");
        sb.AppendLine("    {");

        for (var i = 0; i < mappings.Count; i++)
        {
            var mapping = mappings[i];
            var suffix = i == mappings.Count - 1 ? string.Empty : ",";
            sb.AppendLine($"        {{ (typeof({mapping.SourceTypeDisplayName}), typeof({mapping.DestinationTypeDisplayName})), GeneratedMappings.{mapping.BoxedMethodName} }}{suffix}");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public bool TryGetGeneratedMapper(global::System.Type sourceType, global::System.Type destinationType, out global::System.Func<object, object>? mapper)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _mappers.TryGetValue((sourceType, destinationType), out mapper);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}